model:
  name: gpt2-medium-pt
  hf_model_name: openai-community/gpt2-medium
  tokenizer: gpt2
  context_length: 1024
  embedding_dim: 1024
  nb_layers: 24
  pad_token: -100
  token_dropout_rate: 0.1

  attention:
    nb_heads: 16
    dropout_rate: 0.1
    use_bias: True
    use_mask: True

  transformer_block:
    expand_factor: 4
    dropout_rate: 0.1

  sampler:
    max_length: 100
    temperature: 1.0
    top_k: 3
